version: '3.8'

services:
  catalog.api:
    container_name: lde.catalog.api
    build:
      context: .
      dockerfile: src/Catalog.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionString=Host=localhost; Port=5432; User Id=postgres; Password=postgres; Database=catalog;
      - DOCKER_ENV=true
    depends_on:
      - postgres
    ports:
      - 5601:5601
 
  identityserver:
    container_name: lde.identityserver
    build:
      context: .
      dockerfile: src/IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5601
      - CatalogApi=http://localhost:5601
    ports:
      - 7001:7001

  nginx:
    image: nginx:latest
    volumes:
      - ./proxy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/Catalog.API/Pics:/images
    ports:
      - "80:80"

  postgres:
    image: postgres
    container_name: lde.postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
 
networks:
  default:
    driver: bridge
    internal: false
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.4/24
          gateway: 192.168.0.4